### ISSUE TITLE
An unexpected error occurred: TypeError: Failed to fetch 

### ISSUE THREAD

**Issue by HypnoticKing** [chaiNNer-org/chaiNNer-org.github.io#10]
iterating a folder which had been working flawlessly   Upscaling into a resolution node and saving and now am getting
 Error

An unexpected error occurred: TypeError: Failed to fetch  
after a few minutes of running with no progress.  try to run file independently (upscale then take that image and adjust resolution and just get the circle of death on image and model node.  have restarted computer with no help

**Comment by joeyballentine** [comment]
Hi, this is the GitHub repo for the chaiNNer.app website. Can you reopen this in https://github.com/chaiNNer-org/chaiNNer?
